Add compile job to CI/CD workflow

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -30,3 +30,24 @@ jobs:
                 else
                     exit 0
                 fi
+
+    compile:
+        runs-on: ubuntu-latest
+        container:
+            image: ghcr.io/epitech/epitest-docker:latest
+        steps:
+
+            - name: Checkout Git repository
+              uses: actions/checkout@v4
+
+            - name: compile project
+              run: make
+            
+            - name: check binary
+              run: |
+                if [ ! -f ./swapupcase ]; then
+                    echo "::error title=swapupcase::Binary not found"
+                    exit 1
+                else
+                    exit 0
+                fi
